nosovmik/openvino

inference-engine/src/CMakeLists.txt
model-optimizer/mo/pipeline/unified.py
model-optimizer/requirements.txt
ngraph/CMakeLists.txt
ngraph/frontend/generic/CMakeLists.txt
ngraph/frontend/generic/include/frontend_manager/frontend_manager.hpp
ngraph/frontend/generic/src/frontend_manager.cpp
ngraph/frontend/paddlepaddle/include/paddlepaddle_frontend/model.hpp
ngraph/frontend/paddlepaddle/src/model.cpp
ngraph/python/CMakeLists.txt
ngraph/python/src/pyngraph/frontend_manager.cpp

- Python bindings for P1 methods of frontend API
- 52266

Python bindings for P1 methods of frontend API

---

ngraph/frontend/paddlepaddle/include/paddlepaddle_frontend/model.hpp
ngraph/frontend/paddlepaddle/src/frontend.cpp
ngraph/frontend/paddlepaddle/src/model.cpp

- *Implement getOutputs*
- *Implement getInputs*
- *52771, 52772*

Implement getInputs and getOutputs

---

model-optimizer/automation/package_BOM.txt
model-optimizer/mo.py
model-optimizer/mo/__main__.py
model-optimizer/mo/graph/graph.py
model-optimizer/mo/main.py
model-optimizer/mo/main_test.py
model-optimizer/mo/pipeline/unified.py
model-optimizer/mo/utils/cli_parser.py
model-optimizer/mo/utils/frontendmanager_wrapper.py
ngraph/python/src/ngraph/__init__.py
ngraph/python/src/ngraph/impl/__init__.py

- Create FrontEndManager in MO in only one place
- Reverted old TODO after merge
- N/A

Create FrontEndManager in MO in only one place

---

model-optimizer/mo/front/extractor.py
model-optimizer/mo/pipeline/unified.py

Usage example:
./mo.py --framework pdpd --input_model ../ngraph/test/files/paddlepaddle/models/2in_2out/2in_2out.pdmodel --log_level=INFO --input inputX1,inputX2 --input_shape [1,1,4,4],[1,2,3,4]
- N/A

SetPartialShape in MO

---

ngraph/test/frontend/paddlepaddle/partial_shape.cpp
ngraph/test/frontend/shared/src/basic_api.cpp
ngraph/test/frontend/shared/src/cut_specific_model.cpp

- Add ASSERT_NO_THROW to basic tests for 'Place::getNames'
- Correction of partial_shape tests
- N/A

Correction of partial_shape tests

---

ngraph/frontend/generic/include/frontend_manager/frontend_manager.hpp
ngraph/frontend/generic/src/frontend_manager.cpp
ngraph/frontend/paddlepaddle/include/paddlepaddle_frontend/place.hpp
ngraph/frontend/paddlepaddle/src/frontend.cpp
ngraph/frontend/paddlepaddle/src/model.cpp
ngraph/frontend/paddlepaddle/src/place.cpp

- *Fix OutPlace implementation: One OutPlace must correspond one TensorPlace*
- 
- *52251*

Fix OutPlace implementation: One OutPlace must correspond one TensorPlace

---

model-optimizer/mo/front/extractor.py
model-optimizer/mo/pipeline/unified.py
ngraph/test/frontend/shared/src/cut_specific_model.cpp

- OverrideAllInputs, if only inputs are different
- OverrideAllOutputs, if only outputs are different
- ExtractSubgraph, if both inputs/outputs are changed
- SetPartialShape if new shape is specified for inputs
- 52268

Initial support of reshape and change inputs/outputs

---

ngraph/python/tests/test_ngraph/test_frontendmanager.py

- Currently only basic FrontEndManager API, as there is no test PDPD models, and there is no guarantee that PDPD frontend is enabled
- 52266

Test for python bindings

---

model-optimizer/automation/package_BOM.txt
model-optimizer/extensions/front/user_data_repack.py
model-optimizer/mo/front/extractor.py
model-optimizer/mo/front_ng/__init__.py
model-optimizer/mo/front_ng/extractor.py
model-optimizer/mo/front_ng/frontendmanager_wrapper.py
model-optimizer/mo/front_ng/pipeline.py
model-optimizer/mo/front_ng/serialize.py
model-optimizer/mo/graph/graph.py
model-optimizer/mo/main.py
model-optimizer/mo/pipeline/unified.py
model-optimizer/mo/utils/cli_parser.py
model-optimizer/mo_pdpd.py

- Separate ngraphFrontend-related code from other
- 52268

Separate ngraphFrontend-related code from other

---

ngraph/frontend/paddlepaddle/src/model.cpp

- *Some models don't have weights and no .pdiparams file because of that*

Fix issue with models without weights

---

ngraph/frontend/paddlepaddle/include/paddlepaddle_frontend/model.hpp
ngraph/frontend/paddlepaddle/src/frontend.cpp
ngraph/frontend/paddlepaddle/src/model.cpp
ngraph/test/frontend/paddlepaddle/cut_specific_model.cpp
ngraph/test/frontend/shared/include/cut_specific_model.hpp
ngraph/test/frontend/shared/src/cut_specific_model.cpp

- *Implement setTensorValue in InputModelPDPD*
- *53097*

Implement setTensorValue in InputModelPDPD

---

ngraph/frontend/paddlepaddle/include/paddlepaddle_frontend/model.hpp
ngraph/frontend/paddlepaddle/src/frontend.cpp
ngraph/frontend/paddlepaddle/src/model.cpp

- *Previously each block was stored in a different map which is incorrect. Now ops from all blocks get into one map.*

Support multiple blocks

---

model-optimizer/mo/front_ng/extractor.py
model-optimizer/mo/front_ng/pipeline.py
ngraph/python/src/pyngraph/frontend_manager.cpp

- Example: ./mo_pdpd.py --input_model <path>/relu.pdmodel --input xxx{f16}
- 52267

Support of setElementType in MO

---

ngraph/test/frontend/paddlepaddle/load_from.cpp
ngraph/test/frontend/shared/src/load_from.cpp

- *item1*
- *...*
- *ticket-id*

Updated generated models path for load_from test cases

---

.ci/azure/linux.yml
ngraph/test/CMakeLists.txt

- *item1*
- *...*
- *ticket-id*

Skip PDPD unit tests if python3 or pip paddlepaddle is not installed

---

model-optimizer/mo/main.py
model-optimizer/mo/main_pdpd.py
model-optimizer/mo/utils/cli_parser.py

- Old version breaks existing private tests which use cli_parser directly
- *ticket-id*

MO fix in get_all_cli_parser

---

CMakeLists.txt
ngraph/CMakeLists.txt

Otherwise, there are problems with unloading of PDPD frontend and loading again
Ref: https://stackoverflow.com/questions/37051635

Build ProtoBuf as static lib, not dynamic

---

model-optimizer/mo/front_ng/frontendmanager_wrapper.py

- *item1*
- *...*
- *ticket-id*

MO: fix after exceptions commit

---

CMakeLists.txt

- *item1*
- *...*
- *ticket-id*

Enable onnx importer back

---

ngraph/frontend/paddlepaddle/src/op/pool2d.cpp
tests/fuzz/README.md
tests/fuzz/fuzz-testhelper/tokenizer.h
tests/fuzz/scripts/init_corpus.py
tests/fuzz/src/CMakeLists.txt
tests/fuzz/src/import_pdpd-fuzzer.cc

Adds fuzzing test for frontend API importing PDPD models

Add pdpd fuzz test

---

ngraph/python/mock_py_frontend/mock_py_ngraph_frontend/mock_py_frontend.hpp
ngraph/python/src/pyngraph/frontend_manager.cpp
ngraph/test/CMakeLists.txt
ngraph/test/frontend/frontend_manager.cpp
ngraph/test/frontend/paddlepaddle/basic_api.cpp
ngraph/test/frontend/paddlepaddle/cut_specific_model.cpp
ngraph/test/frontend/paddlepaddle/exceptions.cpp
ngraph/test/frontend/paddlepaddle/load_from.cpp
ngraph/test/frontend/paddlepaddle/op.cpp
ngraph/test/frontend/paddlepaddle/partial_shape.cpp
ngraph/test/frontend/paddlepaddle/set_element_type.cpp
ngraph/test/frontend/shared/include/basic_api.hpp
ngraph/test/frontend/shared/include/load_from.hpp
ngraph/test/frontend/shared/include/op.hpp
ngraph/test/frontend/shared/include/partial_shape.hpp
ngraph/test/frontend/shared/include/set_element_type.hpp
ngraph/test/frontend/shared/include/utils.hpp
ngraph/test/frontend/shared/src/basic_api.cpp
ngraph/test/frontend/shared/src/cut_specific_model.cpp
ngraph/test/frontend/shared/src/load_from.cpp
ngraph/test/frontend/shared/src/op.cpp
ngraph/test/frontend/shared/src/partial_shape.cpp
ngraph/test/frontend/shared/src/set_element_type.cpp

- And corresponding fixes
- *...*
- *ticket-id*

Proper enabling clang check for frontend-specific tests

---

ngraph/frontend/paddlepaddle/src/op_table.cpp

- *Fix depthwise_conv2d_transpose*

fix depthwise_conv2d_transpose

---

ngraph/frontend/paddlepaddle/src/op/split.cpp

fix split with AxisTensor input

---

ngraph/test/frontend/frontend_manager.cpp

- *FrontEnd exception unit tests*

FrontEnd exception unit tests

---

ngraph/frontend/frontend_manager/include/frontend_manager/frontend_exceptions.hpp

Imports for FE exception classes
